-- Tabela de Usuário
CREATE TABLE "Usuario" (
                           "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "nome" VARCHAR2(255) NOT NULL,
                           "cpfCnpj" VARCHAR2(20) NOT NULL,
                           "email" VARCHAR2(255) NOT NULL,
                           "telefone" VARCHAR2(15),
                           "senha" VARCHAR2(255) NOT NULL,
                           "ativo" CHAR(1),
                           "dataCriacao" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           "dataAtualizacao" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Operações de Usuário
-- POST: Criar um novo usuário
-- INSERT INTO "Usuario" (nome, cpfCnpj, email, telefone, senha, ativo) VALUES (?, ?, ?, ?, ?, 'S');

-- GET: Obter um usuário por ID
-- SELECT * FROM "Usuario" WHERE "id" = ?;

-- GET: Listar todos os usuários
-- SELECT * FROM "Usuario";

-- PUT: Atualizar os dados de um usuário
-- UPDATE "Usuario" SET nome = ?, cpfCnpj = ?, email = ?, telefone = ?, senha = ?, ativo = ?, dataAtualizacao = CURRENT_TIMESTAMP WHERE id = ?;

-- DELETE: Excluir um usuário
-- DELETE FROM "Usuario" WHERE id = ?;

-- Tabela de Criptomoeda
CREATE TABLE "Criptomoeda" (
                               "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "cryptoId" VARCHAR2(50) NOT NULL,
                               "nomeCripto" VARCHAR2(255) NOT NULL,
                               "simbolo" VARCHAR2(10) NOT NULL,
                               CONSTRAINT "cryptoId_unico" UNIQUE ("cryptoId")
);

-- Operações de Criptomoeda
-- POST: Adicionar uma nova criptomoeda
-- INSERT INTO "Criptomoeda" (cryptoId, nomeCripto, simbolo) VALUES (?, ?, ?);

-- GET: Obter informações de uma criptomoeda
-- SELECT * FROM "Criptomoeda" WHERE "id" = ?;

-- GET: Listar todas as criptomoedas
-- SELECT * FROM "Criptomoeda";

-- PUT: Atualizar dados de uma criptomoeda
-- UPDATE "Criptomoeda" SET nomeCripto = ?, simbolo = ? WHERE id = ?;

-- DELETE: Excluir uma criptomoeda
-- DELETE FROM "Criptomoeda" WHERE id = ?;

-- Tabela de Item de Carteira (WalletItem)
CREATE TABLE "ItemCarteira" (
                                "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "usuarioId" NUMBER NOT NULL,
                                "criptomoedaId" NUMBER NOT NULL,
                                "quantidade" NUMBER(15, 8) NOT NULL,
                                CONSTRAINT "fk_usuario" FOREIGN KEY ("usuarioId") REFERENCES "Usuario"("id") ON DELETE CASCADE,
                                CONSTRAINT "fk_criptomoeda" FOREIGN KEY ("criptomoedaId") REFERENCES "Criptomoeda"("id") ON DELETE CASCADE
);

-- Operações de Item de Carteira
-- POST: Adicionar um item à carteira de um usuário
-- INSERT INTO "ItemCarteira" (usuarioId, criptomoedaId, quantidade) VALUES (?, ?, ?);

-- GET: Obter um item de carteira por ID
-- SELECT * FROM "ItemCarteira" WHERE id = ?;

-- GET: Listar todos os itens da carteira de um usuário
-- SELECT * FROM "ItemCarteira" WHERE usuarioId = ?;

-- PUT: Atualizar a quantidade de uma criptomoeda na carteira
-- UPDATE "ItemCarteira" SET quantidade = ? WHERE id = ?;

-- DELETE: Excluir um item da carteira
-- DELETE FROM "ItemCarteira" WHERE id = ?;

-- Tabela de Transação
CREATE TABLE "Transacao" (
                             "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "usuarioId" NUMBER NOT NULL,
                             "criptomoedaId" NUMBER NOT NULL,
                             "quantidade" NUMBER(15, 8) NOT NULL,
                             "precoUnitario" NUMBER(15, 2) NOT NULL,
                             "valorTotal" NUMBER(15, 2) NOT NULL,
                             "tipo" VARCHAR2(10) CHECK ("tipo" IN ('compra', 'venda')) NOT NULL,
                             "dataHora" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             CONSTRAINT "fk_usuario_transacao" FOREIGN KEY ("usuarioId") REFERENCES "Usuario"("id") ON DELETE CASCADE,
                             CONSTRAINT "fk_criptomoeda_transacao" FOREIGN KEY ("criptomoedaId") REFERENCES "Criptomoeda"("id") ON DELETE CASCADE
);

-- Operações de Transação
-- POST: Criar uma nova transação
-- INSERT INTO "Transacao" (usuarioId, criptomoedaId, quantidade, precoUnitario, valorTotal, tipo) VALUES (?, ?, ?, ?, ?, ?);

-- GET: Obter detalhes de uma transação
-- SELECT * FROM "Transacao" WHERE id = ?;

-- GET: Listar transações de um usuário
-- SELECT * FROM "Transacao" WHERE usuarioId = ?;

-- PUT: Atualizar dados de uma transação
-- UPDATE "Transacao" SET quantidade = ?, precoUnitario = ?, valorTotal = ?, tipo = ?, dataHora = CURRENT_TIMESTAMP WHERE id = ?;

-- DELETE: Excluir uma transação
-- DELETE FROM "Transacao" WHERE id = ?;
